---
name: "evcc 2"
version: 0.211.1
slug: evcc2
description: "EV Charge Controller 2!"
url: https://github.com/evcc-io/evcc
arch: 
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
startup: application
panel_icon: mdi:ev-station
panel_admin: false
panel_title: EVCC 2
boot: auto
legacy: true
stage: stable
ingress: true
ingress_port: 7071
init: false
watchdog: http://[HOST]:[PORT:7071]
image: evcc/evcc
options: 
  sqlite_file: /data/evcc.db
  config_file: /config/evcc.yaml
schema:
  sqlite_file: str
  config_file: str?
  EVOPT_URI: url?
  SEMP_BASE_URL: url?
host_network: false
map: 
  - type: addon_config
    read_only: False
  - type: homeassistant_config
    read_only: False
uart: true
webui: http://[HOST]:[PORT:7071]/
ports:
  7070/tcp: 7071
  4712/tcp: 4712
  5200/tcp: 5200
  5201/tcp: 5201
  5353/udp: 5353
  7050/tcp: 7050
  7090/udp: 7090
  8887/tcp: 8887
  8899/udp: 8899
  9522/udp: 9522
ports_description:
  7070/tcp: "EVCC UI"
  4712/tcp: "EEBUS"
  5200/tcp: "Modbus Proxy"
  5201/tcp: "Modbus Proxy (multi port)"
  5353/udp: "Multicast DNS (mDNS)"
  7050/tcp: "evopt API"
  7090/udp: "Keba"
  8887/tcp: "OCPP web socket"
  8899/udp: "Modbus UDP"
  9522/udp: "SMA Speedwire Multicast"
